name: Release

on:
  push:
    branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2

      - run: bun install --frozen-lockfile

      - name: Create or update Version PR
        id: changesets
        uses: changesets/action@v1
        with:
          version: bunx changeset version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag release
        if: startsWith(github.event.head_commit.message, 'Version Packages') && steps.changesets.outputs.hasChangesets == 'false'
        run: bun run tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
